---
title: "Projet jeu du blackjack"
---
# Présentation du jeu
## Déroulement d'une partie
- 6 jeux de carte sont défini et mélangé (52 cartes, pas de joker)
- Le joueur appuie sur un bouton pour démarrer la partie
- Le programme distribue deux cartes retournées au joueur
- Le programme distribue une carte retournée et une carte cachée a l'ordi
- Les points sont calculés et affichés au joueur
- Le joueur doit choisir entre laisser l'ordi jouer ou retirer une carte
- *S'il décide de tirer une carte :
    - Si le nombre de points est = 21, il a gagné et le jeu s'arrette
    - Si le nombre de points est >21, il a perdu et le jeu s'arrette
    - Si le nombre de points inferieur à 21, il peut décider de rejouer* ou de s'arretter**
- **S'il décide de s'arretter, l'ordi va retourner la carte cachée :
    - Si il tombe sur 21, l'ordi gagne
    - Si son nombre de points est inferieur à 18, il retourne une carte
    - Si son nombre de points est superieur à 18 (entre 18 et 21), il s'arrette
    - Si son nombre de points est superieur à 21, le joueur gagne

## Valeurs des cartes
-  2 à 10 -> valeur de la carte
- Valet, dame, roi -> 10
- As ->
    - 11 si en ajoutant 11 à la main, le score est inférieur ou égal à 21.
    - 1 si en ajoutant 11, le score dépasse 21.

## Idées supplémentaires
- Ajouter une fonctionnalité de pari : le joueur peut parier des jetons sur sa réussite.
- Jouer à plusieurs.
- Ajouter un timer.

# Jeu dans le terminal
## Structure du projet en Julia
- Fichier carte.jl : Pour définir la classe carte (attributs : String nom, Int valeur, image interface graphique)
- Fichier deck.jl : Pour définir la classe deck (attributs : list de carte. Méthode : distribuer une carte (choisir une carte au hasard, la mettre dans la main de quelquu'un et l'enlever dans la liste de carte du deck))  Note : 6x52 cartes pour 1 deck de base.
- Fichier jeu.jl : Pour définir la classe de jeu (attributs : deck, deux main_cartes (ordi + joueur))
- Fichier main.jl : fonction générale avec les boucles de jeu.

# Jeu dans un notebook Pluto (tentative)
Explication

